os: linux
dist: bionic

language: python
python: 3.7

addons:
  apt:
     packages:
     - gfortran
     - libblas-dev
     - liblapack-dev
     - ninja-build
  homebrew:
     update: true
     packages:
     - gcc
     - lapack
     - ninja

jobs:
  include:
  - os: linux
  - os: osx
    env: FC=gfortran
    language: minimal

install:
  - pip3 install meson

script:
  - meson build_gcc --buildtype release -Dla_backend=netlib
  - ninja -C build_gcc
